"""create sync jobs table

Revision ID: 19f2c729c9c6
Revises: f5a2426418ee
Create Date: 2026-08-14 13:33:25.318948

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "19f2c729c9c6"
down_revision: str | Sequence[str] | None = "f5a2426418ee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sync_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default="pending", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=50), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'completed', 'failed')",
            name="ck_sync_jobs_status",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_sync_jobs_status_created_at",
        "sync_jobs",
        ["status", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_sync_jobs_user_id_created_at",
        "sync_jobs",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "uq_sync_jobs_active_user",
        "sync_jobs",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('pending', 'running')"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_sync_jobs_active_user",
        table_name="sync_jobs",
        postgresql_where=sa.text("status IN ('pending', 'running')"),
    )
    op.drop_index("ix_sync_jobs_user_id_created_at", table_name="sync_jobs")
    op.drop_index("ix_sync_jobs_status_created_at", table_name="sync_jobs")
    op.drop_table("sync_jobs")
    # ### end Alembic commands ###
